### ISSUE TITLE
Allow "closing" room by ESC / ESCAPE key

### ISSUE THREAD

**Issue by Mikaela** [Nheko-Reborn/nheko#1034]
### The Problem

I noticed that I can get back to the "no room open" by clicking the room again. Other apps such as Telegram desktop allow getting there by pressing ESC on keyboard, which I find more intuitive.

### The Solution

I would like to be able to get there also in Nheko by pressing ESC so I don't have to keep a room open and won't accidentally mark anything as read.

### Alternatives

I could keep spending very small amount of time by just clicking the room again or ignore the issue and possibly be reading things I am not actually reading

### Additional context

I love the feature and get the impression that so does @LorenDB considering the ban on anyone else touching that code if I am reading https://github.com/Nheko-Reborn/nheko/issues/730#issuecomment-960238986 correctly.

I am on nheko 0.9.3 a100a5b2 from the nightly flatpak repo on Fedora 35.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by LorenDB** [comment]
I've also considered Ctrl+W, as used in web browsers to close tabs.

**Comment by Mikaela** [comment]
My muscle memory knows ESC, and I have faint idea of Slack and Mattermost supporting it too

**Comment by deepbluev7** [comment]
I think Escape just is the wrong key for this. It already closes:

- completers (like emojis, rooms, etc)
- edits
- replies
- image popups
- right click menus
- room settings
- etc

Sometimes I hit it multiple times to close stuff. Usually I want to still be in the room at the end. Giving Escape also the option to close the current room makes it very hard to get back to the room, because you might need to search for the room again. I would prefer something like Ctrl-W.
