### ISSUE TITLE
Secure storage issue

### ISSUE THREAD

**Issue by hnhx** [Nheko-Reborn/nheko#1099]
### Describe the bug

I'm on Debian Sid, I tried to setup gnome-keyring without any success, nheko didn't let me login, then I tried keepassxc which resulted in nheko overwriting my main keepassxc file where I keep my password, thankfully I had a backup. I hate this secure storage feature with a burning passion, why isn't there an option to just simply disable it? I have no use for it.

### To Reproduce

Login to nheko

### What happened?

nheko quits due to secure storage issue.

### Expected behavior

Work like any other Matrix client....

### Version

0.9.3-2

### Desktop Environment

dwm

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
There is an option to disable it, it is just not documented, since it stores all your encryption keys in plain text and we don't want to take responsibility for you disabling the database encryption. You can find the settings name and location by looking through the PRs or checking the UserSettings.cpp file.
