### ISSUE TITLE
Unable to launch a new instance of nheko if neko is already started from an another session.user

### ISSUE THREAD

**Issue by dr41nU** [Nheko-Reborn/nheko#113]
Hello,
Thanks for supporting this nice application.
I opened this issue since it seems that the verification of already running instance does not care about multiple users/sessions

### System:

- Nheko version: 0.6.4-1b34b53 | Linux
- Installation method: Gentoo ebuild
- Operating System: Gentoo
- Qt version: qtgui-5.13.2
- C++ compiler: gcc-9.2.0-r2
- Desktop Environment: Gnome 3.32.2

### Actual behavior

If nheko is already started on a X session for a user, the launch of a new instance for another user on a other session on the same host is failing with the error "another instance of nheko is running"

![image](https://user-images.githubusercontent.com/50152843/74185441-f2052080-4c48-11ea-8449-a7258c50876b.png)

### Expected behavior

Be able to start a new instance for a other user or X session

### Steps to reproduce

1. Log into user A from GDM (for exemple).
2. Start nheko
3. Do not close X session
4. Log into user B
5. Start nheko

### Logs
N/A

### Debugger backtrace
None

**Comment by deepbluev7** [comment]
This would basically be fixed, when my proposed solution to #84 gets implemented.

**Comment by redsky17** [comment]
@deepbluev7 I'm not entirely sure that will fix the issue, since nheko isn't even running as the same user.  Think about multiple users logged into one workstation via VNC or similar.

**Comment by redsky17** [comment]
Also, I think that this is enough of a thorn in user's sides that we should target it for the 0.7.0 release

**Comment by deepbluev7** [comment]
Yeah, we should target 0.7.0 for that. If you look at my proposed solution of using the [3rd party SingleApplication replacement of QApplication](https://github.com/itay-grudev/SingleApplication), that has flags for per user application instances, so it probably handles multiple users correctly. Currently our issue is, that we use a global shared mem segment. If we use a per user one or even better, one per login session/XDG_CACHE_DIR, we would solve the activation of nheko instead of opening the popup, multiple instances per user, etc all at once.

**Comment by deepbluev7** [comment]
I think I fixed this now.

**Comment by dr41nU** [comment]
I can confirm that it works like a charm now. Many thanks
Sorry for the late reply

**Comment by deepbluev7** [comment]
No worries, thanks for the confirmation!
