### ISSUE TITLE
Automatically logged out if used with shared /home partition

### ISSUE THREAD

**Issue by 0verEngineer** [Nheko-Reborn/nheko#1204]
### Describe the bug

Environment:
- Nheko installed as Flatpak
- /home Partition shared between 2 Fedora installations, one with KDE the other one with Gnome

If i boot into the other installation and start Nheko i will be logged out with the Message: "Failed to restore OLM account. Please login again."

### To Reproduce

1. Share /home partition between two linux installs
2. Log into your Matrix account with Nheko
3. Boot into the other installation
4. Start Nheko
5. Reboot into the first installation
6. You will be logged out

### Expected behavior

Both sessions should be able to be logged in simultaneously.

### Version

0.10.2

### Operating system

Linux

### Installation method

Flathub

### Desktop Environment

KDE, Gnome

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Your config file and database will be shared, but since your secrets are stored in your system specific secrets storage (gnome keyring, kwallet), you won't be able to decrypt the database. So such a setup is not supported. You can use different profiles though to work around that, you just need to make sure the different systems start the right profile.

**Comment by deepbluev7** [comment]
Closing this, as there is no support for a shared home planned, but you can probably find a solution yourself by using the right credential manager.
