### ISSUE TITLE
Figure out if X-Flatpak-RenamedFrom is useful for us

### ISSUE THREAD

**Issue by deepbluev7** [Nheko-Reborn/nheko#1228]
### The Problem

We currently have 2 names for the app, nheko  and io.github.NhekoReborn.nheko (and maybe im.nheko.nheko in the future). Maybe X-Flatpak-RenamedFrom can make that less confusing and simplify our code

### The Solution

Read the docs for X-Flatpak-RenamedFrom

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by LorenDB** [comment]
Related: #1211

**Comment by deepbluev7** [comment]
Additionally we need to migrate the flatpak id to either io.github.Nheko-Reborn or im.nheko, so we probably want to do the latter using this approach.

**Comment by deepbluev7** [comment]
We changed the flatpak id now, so I guess we need to figure out the migration path now.

**Comment by YtvwlD** [comment]
Did you figure something out? If I understood correctly, 0.12.0 has been released with a new flatpak id and I wasn't offered an update from 0.11.3, because the id is different.

According to https://github.com/flatpak/flatpak/issues/4253, this could be solved by pushing a new update to the old id with `flatpak build-export --end-of-life-rebase=newid`.

**Comment by deepbluev7** [comment]
We pushed the new appid first, the eol-rebase should be live only since today, which should prompt for an update now and even migrate app data, it seems.
