### ISSUE TITLE
Support editing messages

### ISSUE THREAD

**Issue by koalp** [Nheko-Reborn/nheko#134]
Currently, we cannot edit messages in nheko, but we can in riot.

It would be nice to be able to edit messages

**Comment by deepbluev7** [comment]
Yes, this would be nice to have. Since we have other priorities right now, we actually listed that as one of the possible GSoC projects. This also isn't currently in the official Matrix Spec. The proposal for it is still in review: https://github.com/matrix-org/matrix-doc/pull/1849

Since no client actually implements, what is stated in that proposal, but uses different names for the relations etc, we would have to reverse engineer, what other clients do... So I'd rather wait for the official spec in this case. If someone is interested in implementing that, I would be willing to help out anytime though!

**Comment by FantasyCookie17** [comment]
Another nice feature to have, that would set Nheko apart from competitors, is `sed`-style regex replace (as in `s/original/edit/g`). Having some `/` command for this, that somehow offers an option to specify the message one wants to edit (for example by adding `2` to select the messsage one sent 2 messages before the last one), while perhaps defaulting to the last one (`0` in my example) sent by that user, would be quite nice.
