### ISSUE TITLE
Remove the need to use dbus to run the program

### ISSUE THREAD

**Issue by kyronsaif** [Nheko-Reborn/nheko#1390]
### The Problem

I feel as if dbus shouldn't be a hard requirement to run nheko, because it is heavily bloat and I don't see the purpose in having it in the first place. Plus, (as far as I know), it is also a security issue.

### The Solution

Make dbus an optional dependency for running nheko.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
DBus is used to show notifications, update the notification count in the task entry, expose an API to allow external applications switch rooms, set a status message, etc. At least the first one is what most people expect from a chat application. DBus is required for that on Linux. So it isn't "bloat", since it is actually the only way to properly provide this feature on different Linux distributions and environments.

You can run Nheko without dbus, if you have built it against dbus. It will just take 30s to launch usually. We have no plan to make DBus optional at built-time or in general. If you want that, patch it out yourself. Also your claims about security issues are not really helpful, since a proper dbus enabled system also adds security by having proper message passing between clients instead of directly accessing each others memory or files.
