### ISSUE TITLE
Not able to install nheko using homebrew on Mac OS X 11.1

### ISSUE THREAD

**Issue by keanpantraw** [Nheko-Reborn/nheko#1401]
### Describe the bug

Nheko bundled in homebrew requires Mac OS X 11.7 and refuses to run on Mac OS X 11.1 despite the fact that README mentions that macos >= 10.14 should work.

### To Reproduce

1. Execute `brew install --cask nheko`
2. Open nheko

### What happened?

Pop-up with following text appears:

You can’t use this version of the application “Nheko” with this version of macOS.

You have macOS 11.1. The application requires macOS 11.7 or later.

### Expected behavior

Nheko should open

### Screenshots

<img width="264" alt="Screenshot 2023-03-03 at 19 17 31" src="https://user-images.githubusercontent.com/1095329/222757528-0d0cb331-6fba-4c92-a4d2-52fa3d69f88a.png">

### Version

0.11.3

### Operating system

macOS

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Does that apply to both of our DMGs from the release on github or just the apple silicon one?

**Comment by redsky17** [comment]
The README is a bit out of date... we require 10.15 these days.  However, it should work on anything Catalina and up for sure, so it's probably an issue where one of the runners is using a too new xcode version.  I'm assuming you're on apple silicon, because the XCode version we use for that is newer than the one we use for Intel builds... which is probably the issue.  I'll have to see if there's a slightly older Xcode available on cirrus-ci for us to use.

**Comment by keanpantraw** [comment]
Nope, it's Intel (MacBook Pro (16-inch, 2019), 2,6 GHz 6-Core Intel Core i7) and macOS Big Sur.

**Comment by deepbluev7** [comment]
Should be fixed by da60aa8802a5f00a1590e3a3b518a19ba82beda1 for the next release. Feel free to download the nightly to verify.
