### ISSUE TITLE
When doing a room search with ctl-k, combine linked rooms and only show me the latest

### ISSUE THREAD

**Issue by benparsons** [Nheko-Reborn/nheko#1442]
### The Problem

When I do a ctl-k search for a name, I see a filtered list of rooms. This is good.

However, some of the rooms are tombstoned, and link to other rooms in the list. I can't see which is the room I actually want to view.

### The Solution

If there are linked, tombstoned rooms, only show me the latest in the search.

### Alternatives

Sort the rooms differently. Have them always sorted by newest, this might lead to better results.

Mark the tombstoned rooms in the search results but keep them in the list.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
So I did go with the alternative in the end, because I sometimes want to jump to tombstoned rooms and I feel like adding shortcut just for that would be weird. So now it sorts by recent "activity" although that is not that well defined. It should work well enough if the recent activity was just messages in both rooms though. And it also makes tombstoned rooms italic. Which isn't that obvious, but I couldn't come up with a better marker.

So I consider this fixed in https://github.com/Nheko-Reborn/nheko/commit/7dd333947711b9ebb54460066a25b07d155fa012 but it might see some iterations in the future :)
