### ISSUE TITLE
Option to disable secure secrets

### ISSUE THREAD

**Issue by realroot2185** [Nheko-Reborn/nheko#1601]
### The Problem

If you don't have a secure secrets service you can't start nehko see https://github.com/Nheko-Reborn/nheko/issues/1187.

### The Solution

The popup with the error could ask you to disable secure secrets, that is the feature request.

If you have encryption it's not necessary to encrypt again or if you don't wish to use secure secrets you have to disable it manually:

https://github.com/Nheko-Reborn/nheko/issues/1187#issuecomment-1255831124.

Edit `~/.config/nheko/nheko.conf`:

```
[General]
run_without_secure_secrets_service=true
```

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
No, disabling secure secrets is not supported since it introduces a security risk. You should ask your OS vendor to fix the secure storage on your platform instead. We only provide that flag for people who want to knowingly disable the secure storage stuff, but we won't provide a UI for it or document it, since we don't want users to use that and then complain.

**Comment by realroot2185** [comment]
My point is:
>If you have encryption it's not necessary to encrypt again or if you don't wish to use secure secrets...

And not I don't have them so let's disable them so nheko won't start otherwise.

Of course users should be warned about messages not encrypted.
But if you wish it to be so or you have LUKS etc.
