### ISSUE TITLE
Allow 12 hour time format in Nheko

### ISSUE THREAD

**Issue by LorenDB** [Nheko-Reborn/nheko#162]
Would it be possible to include support for a 12 hour time format in Nheko (i.e. instead of showing a message as being posted at 14:24, show 2:24 PM)?

**Comment by deepbluev7** [comment]
Well, it would probably be possible, but Qt doesn't have a convenience API to do that, without displaying also the seconds, which we don't want. I think the popup, when you hover over the timestamp, should already display it correctly as AM/PM, depending on your locale, since we just use the long format there iirc.

**Comment by deepbluev7** [comment]
So it seems like this already works, when your locale uses a 12h format :D

**Comment by mehlon** [comment]
My locale uses 12-hour time, but I would prefer 24-hour time. Can this be implemented as a choice?

**Comment by deepbluev7** [comment]
@mehlon You should be able to change your timeformat system wide and nheko should adapt to that, hopefully.
