### ISSUE TITLE
More frequent release cycle?

### ISSUE THREAD

**Issue by hiiamboris** [Nheko-Reborn/nheko#1629]
### The Problem

Last release is close to year old. 

### The Solution

If feasible, please consider building at least twice a year :)

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
We release when a release is ready. Since we just migrated to Qt6, that caused quite a few regressions. So we have the option to either release a worse version or to go through the effort to fix them one by one. You can help out with fixing them, if you want, which would accelerate when we will be able to do a release, but currently that is mostly me fixing the regressions alone and I do have a job and other things to do in my life, which means I can't fix all of them in a week. Some of the fixes even needed fixes in Qt6 itself.

Also currently there are not many Qt themes out yet and there is also no flatpak runtime for the kde frameworks compatible with Qt6 yet, so the ecosystem isn't quite ready for a release yet.

Anyway, our release schedule is done by making sure a release seems reasonably stable. You can help out by testing, reporting bugs and best of all fixing issues. We won't move to a date based schedule, since that will imo lead to worse quality.

**Comment by hiiamboris** [comment]
I would love to test nightly builds if you do provide them :)
Right now there's just nothing to test.
