### ISSUE TITLE
nheko won't start on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by razvbir** [Nheko-Reborn/nheko#1646]
### Describe the bug

Starting nheko produces an error message:

```
nheko
nheko: symbol lookup error: /lib64/libcoeurl.so.0.3: undefined symbol: _ZN6spdlog7details7log_msgC1ENS_10source_locEN3fmt2v917basic_string_viewIcEENS_5level10level_enumES6_
```

### To Reproduce

```
sudo zypper addrepo https://download.opensuse.org/repositories/network:messaging:matrix/openSUSE_Tumbleweed/network:messaging:matrix.repo
sudo zypper ref
sudo zypper in nheko
```

### What happened?

nheko won't start

### Expected behavior

nheko launches

### Version

nheko-0.11.3-3.29.src

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

KDE

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
no
```

### Backtrace

```shell
no
```

**Comment by LorenDB** [comment]
That's because 0.11.3 no longer builds against the latest spdlog, and openSUSE disabled nheko builds until we release a new version that fixes that. Unfortunately, your options for fixing that are pretty limited; maybe use a different client or install the flatpak? Otherwise, I think we are getting closer to a new release, so hopefully nheko builds will work again soon.

**Comment by deepbluev7** [comment]
Closing this, since this is purely a packaging issue.
