### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ozky84** [Nheko-Reborn/nheko#1690]
### Describe the bug

Is there any eta to new release?
As stable is like 1 year old...
Can edit bug if needed...

### To Reproduce

Release

### Version

git

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Did you use profiles?

- [ ] Profiles used?

**Comment by ozky84** [comment]
Mageia Linux devs like if have new release, we have some bug about it we have some problems with Nheko...
https://bugs.mageia.org/show_bug.cgi?id=32965
Take a look this bugreport...

**Comment by LorenDB** [comment]
First, we aren't going to rush the release. We're working on stabilizing a few things from the Qt 6 port, after which there should be a new release.

Second, IIRC the issue in the linked bug report has been mentioned before and IMO appears to be a Qt issue rather than an issue on our end. (Potentially related to #1564 FWIW)

We appreciate your understanding of this. Just bear with us, there should be a new release before too long :)

**Comment by ozky84** [comment]
Okay thanks

**Comment by ozky84** [comment]
yes thanks, i forgot this so good you noticed and closed this.
