### ISSUE TITLE
Hide nested spaces from sidebar

### ISSUE THREAD

**Issue by RoblKyogre** [Nheko-Reborn/nheko#1698]
### The Problem

Currently, when in a space that has a lot of nested spaces (for example the discord space created by mautrix-discord), every single space is shown in the sidebar, cluttering it up.

### The Solution

Add an option to hide spaces that are nested within another space that the user is in.

### Alternatives

Only thing I can think of is hiding the sidebar, but that defeats the purpose of organizing rooms into spaces.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Have you tried:

1. dragging out the sidebar to make it wider
2. Collapsing the space
3. Narrowing it again

**Comment by RoblKyogre** [comment]
oop, didn’t think to try that 😅
thanks, does what i wanted it to do!

**Comment by LecrisUT** [comment]
> Have you tried:
> 
>     1. dragging out the sidebar to make it wider
> 
>     2. Collapsing the space
> 
>     3. Narrowing it again

That was not intuitive. There could be 3 UX improvements on this:
1. Indicate that a space has children (open or closed) in the minimal sidebar
2. Start with space children collapsed (it is more likely they would open the sidebar to search for the missing spaces rather than the opposite)
3. Indicate that the sidebar is expandable. The magnetic snap is quite deceiving
