### ISSUE TITLE
Scaling doesn't seem to work in Windows build

### ISSUE THREAD

**Issue by hiiamboris** [Nheko-Reborn/nheko#1756]
### Describe the bug

Changing 'scaling factor' setting does not affect the UI at all.
Changing 'font size' setting only applies to the messages window, but not to the rest of the UI, which is now a little bit too tight on my screen.

### To Reproduce

Change the aforementioned settings in the Windows build

### Screenshots

Font size 16.00 showcased:

![](https://link.storjshare.io/raw/jxfnjjold7d4xtoupll4mp7ychkq/img/Uk1KG1n.png)

### Version

0.12.0-24c687d5

### Operating system

Windows

### Installation method

Windows download

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
The font size should apply everywhere, you just need to restart Nheko.

**Comment by hiiamboris** [comment]
@deepbluev7 and what about the scale factor? Restart doesn't help with it.

**Comment by hiiamboris** [comment]
Ah, I saw the commit now, nvm.

**Comment by kleinesfilmroellchen** [comment]
Could you please make a fix release for this change? It is keeping me from upgrading from 0.11.3, which is broken thanks to deprecated attachment endpoints. I tried building my own version and gave up after about a day of work. It has now been several months since both the fix has been pushed and the last release was made.

**Comment by kleinesfilmroellchen** [comment]
(I should also mention that the nightly build links are broken.)
