### ISSUE TITLE
Random filenames for copy-pasted images

### ISSUE THREAD

**Issue by qcsv** [Nheko-Reborn/nheko#1765]
### The Problem

When pasting an image into Nheko, the filename appears as "clipboard.png" this leaks that the image came from your clipboard.

### The Solution

The filename should instead be a randomly generated filename to preserve the users privacy.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
You can just edit the filename yourself in the file sending dialog. Arguably just always editing that to "clipboard.png" is better for privacy than generating a random one every time, since then there is no way to tell, if that came from the clipboard or not. Also that data is arguably not that much of a privacy leak, the image will be a bigger leak, since the size and content will tell the recipient much more than "oh, it probably was copied to the clipboard at some point".
