### ISSUE TITLE
Support reactions.

### ISSUE THREAD

**Issue by dessalines** [Nheko-Reborn/nheko#181]
**Is your feature request related to a problem? Please describe.**

Riot has had reactions for a while, and they're in the spec now. A few other clients support them but not Nheko yet.

**Comment by deepbluev7** [comment]
relates to #134.

Also, reactions are sadly not in the spec yet. Until they are, I'm probably not going to work on it, since the current spec proposal doesn't match at all what Riot/Web and RiotX implement and even Riot/Web and RiotX differ in some aspects. The current proposal for relations is a minefield of issues, you can read more about that here: https://github.com/matrix-org/matrix-doc/pull/1849

But multiple people expressed interest in implementing this feature in Nheko, so it may come in the near future and I will help out in some capacity. It's just that MSC1849 is really bad currently and since Riot implemented it, everyone thinks, that they are finished, while it is still an alpha or beta feature :D

**Comment by dessalines** [comment]
Just a note, I see the button there now for react, but when I click it, it does nothing. The current reacts are shown tho!

**Comment by deepbluev7** [comment]
This is done, although the emoji picker likely needs a bit of polish still.
