### ISSUE TITLE
missing content.file.mimetype in encrypted images

### ISSUE THREAD

**Issue by MRAAGH** [Nheko-Reborn/nheko#208]
### Describe the bug
Because mimetype is not specified in the "file" object, some clients might fail to process these files properly. When I try to decrypt Nheko's image emxc-s using [this script](https://github.com/poljar/weechat-matrix/blob/master/contrib/matrix_decrypt.py), I get an error saying "Unknown file type: application/octet-stream".

### To Reproduce
1. Send an image using Nheko in an encrypted room
2. View decrypted source (I used Riot for this)
3. Notice that "mimetype" does not appear in "file", it only appears in "info".

### Expected behavior
According to [this section](https://matrix.org/docs/spec/client_server/latest#extensions-to-m-message-msgtypes) in the spec, "file" should contain "mimetype".

### Screenshots
THE EVENT:
```
{
  "content": {
    "body": "example.png",
    "file": {
      "hashes": {
        "sha256": "IEtS983mC+OEoOZuuh4NQogF2aptt9TtFh6pHvjqW30"
      },
      "iv": "XXwYLDro7Tn/urwx84elLw",
      "key": {
        "alg": "A256CTR",
        "ext": true,
        "k": "J2cIJoZdivGMAszJcQJR_qlIqvlN_LM780HQQ1aD9w0",
        "key_ops": [
          "encrypt",
          "decrypt"
        ],
        "kty": "oct"
      },
      "url": "mxc://ponies.im/615fcddd81a70d9cbdd1883b230f249b",
      "v": "v2"
    },
    "info": {
      "h": 500,
      "mimetype": "image/png",
      "size": 26183,
      "w": 500,
      "xyz.amorgan.blurhash": "L25i1I.6{d-.WXjFWBXR]#%0EktP"
    },
    "msgtype": "m.image",
    "url": "mxc://ponies.im/615fcddd81a70d9cbdd1883b230f249b"
  },
  "room_id": "!Silver_Frames_Grades_Silver_Spoon:ponies.im",
  "type": "m.room.message"
}
```

THE ERROR CAUSED BY THIS:
```
maze@bread ~ matrix_decrypt "emxc://sorunome.de:443/_matrix/media/r0/download/ponies.im/615fcddd81a70d9cbdd1883b230f249b?key=J2cIJoZdivGMAszJcQJR_qlIqvlN_LM780HQQ1aD9w0&hash=IEtS983mC%2BOEoOZuuh4NQogF2aptt9TtFh6pHvjqW30&iv=XXwYLDro7Tn%2Furwx84elLw"
Unknown file type: application/octet-stream
```

### System:

- Nheko version: 0.7.1 | Linux
- Installation method: Void repo
- Operating System: Voidlinux x86_64, kernel 5.4.42_1
- Desktop Environment: KDE

**Comment by deepbluev7** [comment]
Actually the section only mentions the mimetype in the example. From the discussion in #matrix-spec I consider that a bug in the example (examples misled me multiple times already and I fixed some of them, but this one I didn't notice). Please fix weechat to use the mimetype in info instead, which is in the spec and is being sent by Nheko. The spec specifically states, that EncryptedFile just replaces the url member of file messages. Imo it would be weird to send a mimetype in that case and I prefer not to duplicate it, when it is already in info. Especially since this complicates handling a lot, when you don't know, which of the mimetypes overrides the other.

You can reopen this, if the spec text changes, but until then I will consider this invalid. :3
