### ISSUE TITLE
Blank chat timeline

### ISSUE THREAD

**Issue by wolneykien** [Nheko-Reborn/nheko#236]
### Describe the bug

Version 0.7.2. The chat timeline is always **blank**. However, there were some messages, visible with version 0.6.2.

### Screenshots

https://ecloud.global/s/5SaZp8NSe9QdkFX

### System:

- Nheko version: 0.7.2
- Installation method: local build
- Operating System: ALT Linux Sisyphus
- Qt version: 5.12.9
- C++ compiler: gcc-c++ 9
- Desktop Environment: MATE, Enlightenment

**Comment by deepbluev7** [comment]
Blank timeline means, that you probably have warnings about missing qml modules in your logs. You need to install those manually, since they are a runtime dependency. See also #177. The full list is distro dependent, and I never heard of yours, so I can't give you any tips, but look for lines like `[2020-04-24 16:48:48.133] [qml] [warning] qrc:/qml/delegates/PlayableMediaMessage.qml:4:1: module "QtMultimedia" is not installed (qrc:/qml/delegates/PlayableMediaMessage.qml:4, )` and try to figure out, which package those are from.

**Comment by wolneykien** [comment]
Thanks! So, my bygreport is a duplicate one, sorry.

**Comment by deepbluev7** [comment]
No worries, that part is a bit confusing. I hope you could solve your issue?

**Comment by wolneykien** [comment]
Yes. Solved and packaged: https://packages.altlinux.org/en/sisyphus/srpms/nheko .
