### ISSUE TITLE
Separate rooms vs direct discussions

### ISSUE THREAD

**Issue by hydrargyrum** [Nheko-Reborn/nheko#296]
**Is your feature request related to a problem? Please describe.**
When you have a lot of rooms and direct discussions, it's good to be able to tell them apart.

**Describe the solution you'd like**
Since conversations are ordered by last activity, it would make sense to have a group of rooms, sorted by activity, and a separate group of direct discussions, sorted by activity. It's easier to find where you want to pursue a conversation.

**Comment by deepbluev7** [comment]
I will never split the room list into two separate lists, since it actually makes it a lot harder to find rooms and interact with the list. I do have planned to add an additional filter on the side to only show direct chat rooms. Splitting the list is simply only an improvement if you have between 10 and 50 rooms. It makes things a lot more confusing, if you have less rooms or more, especially since Matrix really doesn't define a direct chat well. Sometimes a client may accidentally convert your direct chat into a room and otherwise. (Canonical DMs should fix that)

I also plan to add something like a friend list in the future, where you can define a set of users, that you are interested in, to see, if they are online, quickly send them a message and recognize them in shared rooms more easily or so. Still in the planning phase though.

**Comment by JuniorJPDJ** [comment]
It's similar to #317 but mine FR specifies solution I'd get to see.

**Comment by deepbluev7** [comment]
Well, we did add a filter now and I won't segment the room list, so those should be good enough unless someone wants to implement and maintain a different solution.
