### ISSUE TITLE
Toggle weirdness in settings

### ISSUE THREAD

**Issue by deepbluev7** [Nheko-Reborn/nheko#331]
### Describe the bug

They sometimes only move on the second click. Also, if you toggle "minimize to tray", it does not move the toggle, but colors it as enabled.

### To Reproduce
1.Go to Settings
2. Toggle "minimize to tray" on.

### Expected behavior

Start in tray enables and moves to the right.

### Screenshots

![image](https://user-images.githubusercontent.com/16312324/99862303-19eac280-2b91-11eb-86c5-a343283f261e.png)

### System:

- Nheko version: 0.7.2 and master

**Comment by Kirillpt** [comment]
One more thing
### **Describe the bug**


When you toggle off 'minimize to tray, next toggle(start in tray) goes to block, but not off.
### **To Reproduce**
 
Steps to reproduce the behavior:
1. Go to Settings
2. Toggle "minimize to tray" on.
3. Toggle "Start in tray" on.
4. Toggle "minimize to tray" off.
### **Expected behavior**
 

Toggle "Start in tray" goes off and block.
### **Screenshots**
 

![toggle_issue_331](https://user-images.githubusercontent.com/26901389/99914450-89d28780-2d0e-11eb-9c53-cd7861d558ee.png)
