### ISSUE TITLE
arm64 appimage?

### ISSUE THREAD

**Issue by Thatoo** [Nheko-Reborn/nheko#345]
Hello,

Could it be possible to get an appimage for arm64 in order to be able to install element on pinephone, pinetab and so on...

Regards,

**Comment by deepbluev7** [comment]
Unless someone contributes that, this will probably not happen. You can use the flatpak though.

**Comment by Thatoo** [comment]
Well sudo apt install nheko did the job apparently. Awesome.

**Comment by deepbluev7** [comment]
Yeah, that version is probably very old. As I said, the flatpaks should work, at least they do on my devices.

**Comment by Thatoo** [comment]
Flatpak is a burden to me. I'd avoid using nheko if I'm forced to install flatpak for it. I'll wait and see. Thanks.

**Comment by deepbluev7** [comment]
Well, as I said, AppImages are very hard to package correctly, while flatpak provides all the tooling for it. So if you don't like flatpak, you have to either contribute the AppImage stuff yourself or fix the packages for your distribution (or wait for the next stable release). If AppImages could actually be packages reasonably easily, without causing all sort of issues, we could provide that, but sadly that is not the case.

**Comment by Thatoo** [comment]
I understand. Sorry if you felt as I was complaining about the lack of Appimage for arm, that was not my intention.
You do a great job and I didn't want to be negative about it.
I don't know anything about packaging so I can only ask about it. If it's not possible, not available, I understand that, I'll be patient and wait for the next stable release of .deb or an appimage some day. It was just a request as a... reminder maybe.
If some day I was in a situation of learning packaging, I will learn appimage and come helping in here.

Keep on your job with smile and forget about my request. Take care.

**Comment by deepbluev7** [comment]
Ah, sorry, I didn't mean to sound annoyed at you. I'm only annoyed that AppImages are so hard to package and my frustration with them may have come across wrong! It's fine to request anything you like, as you noticed, I'll just say no, if I don't want to do it, but others regularly pick up stale issues and implement them! Anyway, have a nice day! <3

**Comment by deepbluev7** [comment]
I decided to drop the AppImage we provide for now, so this probably will not happen, which is why I am going to close this too. It is just too annoying to maintain. If someone wants to see this come back, please step up and open a PR. It was removed in b27b7c9482ef62e1828f9bd4f804ba4a8bf2b074, which you can use as a starting point. I know, this is not the resolution you probably wanted to see, but maintaining the AppImage is a lot of effort and there are a lot of AppImage specific bugs, which we never solved. We need someone, who actually uses the AppImage, to maintain it.
