### ISSUE TITLE
Render edited messages

### ISSUE THREAD

**Issue by slondr** [Nheko-Reborn/nheko#402]
**Is your feature request related to a problem? Please describe.**
Probably the most immediately-visible difference that makes Nheko look more unrefined/unpolished compared to big-name clients like Element is the ugly handling of edited messages. If someone edits a message, the old message remains and the new one is reprinted with an asterisk in front — this often results in my entire chat window filling up with a single message, or very old messages reappearing when they shouldn't. This is both very ugly and also occasionally prevents me from easily reading the chat history.

**Describe the solution you'd like**
The content of messages should change when they are edited, instead of remaining + a new message appearing.

**Comment by deepbluev7** [comment]
Kinda duplicate to #134. The problem is that I disagree with the current proposal for edits (it is not officially part of the matrix spec at this point). Which is why I didn't implement it, since I was hoping for either the proposal to get fixed or it at least get merged into the spec officially. I probably need to implement it at some point now though, since explaining that every time again is no fun...
