### ISSUE TITLE
New chat is not accessible when it is initiated by other user

### ISSUE THREAD

**Issue by vtronko** [Nheko-Reborn/nheko#42]
### System:

- Nheko version: 0.6.3-0c53a87 | Linux
- Installation method: build
- Operating System: Arch
- Qt version: 5.12.1
- C++ compiler: gcc 8.2.1
- Desktop Environment: KDE
### Actual behavior
New chat entry appears in left sidebar, although it's not clickable and this remains even after reboot.

### Expected behavior
New chats should be accessible at any circumstances.

### Steps to reproduce
Two instances of matrix clients, riot (R), nheko(N).

R user invites N to 1:1 chat.

**Comment by vtronko** [comment]
I've achieved to see an `Accept/Decline` in sidebar once randomly...

**Comment by redsky17** [comment]
I tested a few different times between Riot and Nheko and consistently got the invite on both sides every time, though with some delay in some cases (assuming due to homeserver latency).  I additionally did not have any issues clicking on the new room in Nheko at all.  I agree that the 'Accept Decline' buttons aren't very nice from a UI perspective right now, but I can't reproduce the original issue of having a new chat entry appear that isn't able to be interacted with.  I will see about spinning up a KDE environment and giving it another shot, just in case there's something specific there.

**Comment by vtronko** [comment]
Sorry if I confused you, I can't reproduce it anymore. :(
Only UI part but you know about it anyway.

**Comment by deepbluev7** [comment]
This was actually still a bug, because we never initialized the y value of the buttons, so they were placed at a random vertical position... I fixed that in 932dbf38fe23130cb0b1e4bdcdab7d62e086432b...
