### ISSUE TITLE
Can't open Nheko.app on Mac OS 10.13.6 (but exec from shell works!)

### ISSUE THREAD

**Issue by tntclaus** [Nheko-Reborn/nheko#485]
### Describe the bug
Can't open `Nheko.app` on Mac OS 10.13.6:

```
You have macOS 10.13.6. The application requires macOS 10.14 or later.
```

**But I _can_ execute it from bash this way** (and it works as expected ):
```
/Applications/Nheko.app/Contents/MacOS/nheko
```

### Possible fix

Add `-mmacosx-version-min=10.13` to compiler/linker options

See:
https://stackoverflow.com/a/44692821

### To Reproduce
1. Try to open Nheko.app with double click on Mac OS High Sierra

### Expected behavior
App launches

### System:

- Nheko version: 0.8.1-1a2517e8 | Darwin
- Installation method: latest release
- Operating System: Mac OS X 10.13.6

**Comment by deepbluev7** [comment]
Is there a specific reason, why you can't update to macOS 10.14? We would like to migrate away from the APIs deprecated and replaced in 10.13 at some point, so that's why we chose 10.14 as the current baseline. Do you have a reason for sticking to an older version and why we should still support that release?

**Comment by tntclaus** [comment]
I use macbook pro late 2011 / early 2012  and can't update Mac os. This is still decent hardware and there are plenty of mac users who do not want to switch to newer models.

Which APIs were deprecated? AFAIK the major change between 13 and 14 is metal, which doesn't seem to me as somewhat really important for chat application.

**Comment by tntclaus** [comment]
You use Qt, especially Qml, which in turn uses 3d hardware. Is that APIs you talk about?

**Comment by tntclaus** [comment]
Now I understand why nheko turns on GPU. Well, from macbook users' point of view this makes app literally no different from, say, element (which runs js inside electron/chromium) — both force excess energy consumption for nothing. 

I think for Qt app there is no need to maintain compatibility with older OS X versions.

**Comment by deepbluev7** [comment]
I was talking about the notification API, which got replaced by a new one in macOS 10.14.

> Now I understand why nheko turns on GPU. Well, from macbook users' point of view this makes app literally no different from, say, element (which runs js inside electron/chromium) — both force excess energy consumption for nothing.

I disagree. Using the GPU for rendering usually reduces power consumption by a lot, which is why all rendering on macOS and mobile platforms is done on the GPU. Electron uses a lot of power, because it can use quite a bit of CPU to do simple tasks (Element usually uses 4x as much CPU as Nheko or more). But if you don't like Qt, that's fine, but I believe you are mistaken, that Qt increases energy consumption.

**Comment by tntclaus** [comment]
> I disagree. Using the GPU for rendering usually reduces power consumption by a lot, which is why all rendering on macOS and mobile platforms is done on the GPU.

As a Macbook user I definitely disagree. Enabling discrete GPU instead of integrated GPU draws more power => less time to work from battery (somewhat 6 hours vs 2 hours). That's not my assumption, that's a fact tested literally hundreds times. And it's not about me not liking Qt, it's about guys who take popular tools and who think the tools will do all "cross platform magic" for them. Unfortunately that's not how it works.

**Comment by redsky17** [comment]
It's not because of anything that we are doing.  It's because your iGPU doesn't support features some features of Qt Quick, so Qt needs to use your dedicated GPU: https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-62009

For reference, nheko does not use my dedicated GPU on my newer macbook pro

**Comment by deepbluev7** [comment]
Oh, it uses the dedicated GPU vs the integrated. I did not catch that. That is of course subideal, but seems to be only an issue on older mac books?
