### ISSUE TITLE
Add a way to generate permalinks to messages

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#499]
**Is your feature request related to a problem? Please describe.**
Sometimes you need to share links to events with people online or in other places, it would be nice if the context menu for an event allowed you to copy a link.

**Describe the solution you'd like**
Add options to the context menu for a event to display (and copy to clipboard) both a matrix.to and a `matrix:` URI for an event.

In addition the same options for rooms and users would be nice.

**Comment by deepbluev7** [comment]
I'm currently not sure where to put the room and user links atm, so I am just generating event links for now (the others can be copied via the event completer in the worst case). I also decided to generate matrix.to links for now, since having 2 options to copy events would be confusing and this should be better for sending outside for now, since it links to a website, that explains what Matrix is.
