### ISSUE TITLE
nheko Stuck at "creating new olm account"

### ISSUE THREAD

**Issue by awesomehaze** [Nheko-Reborn/nheko#503]
### Describe the bug
When I launch nheko from the "nheko-git" AUR package, no graphical window is spawned. It appears to be stuck on "creating new olm account," and waiting changes nothing.

### To Reproduce
1. Launch nheko from a terminal

### Expected behavior
I expect that nheko launch.

### Screenshots
![image](https://user-images.githubusercontent.com/48741653/109713798-8e260080-7b99-11eb-8d80-e36c46c635e5.png)

### System:

- Nheko version: 0.7.2.r2316.b6f2acfe-1
- Installation method: nheko-git AUR pkgbuild
- Operating System: Arch Linux
- Desktop Environment: KDE Plasma (x11)

### Logs

The log file at ~/.cache/nheko/nheko/nheko.log is empty

**Comment by awesomehaze** [comment]
Please forgive me if this is an AUR thing.

**Comment by deepbluev7** [comment]
Ups, sorry I missed this issue. Anyway, this is a bug in your BIOS actually. You are on a Ryzen 3000 CPU and didn't update your BIOS to include the RDSEED fixes and such (Agesa 1.1.3ABBA or so?). Because of that, the C++ standard library can't generate random numbers for the random number generation functions. You need those for the secret keys to enable encryption to be secure. We don't really have control over that hang, since the random function just hangs, when you call it, and there is no way for us to know in advance. Since you probably don't want your key to be 0xffffffffffffffffffffffff, I would suggest you update your BIOS. Please be aware, that updating your Bios is risky and may break your hardware, so I take no responsibility! I hope that helps.

**Comment by awesomehaze** [comment]
Awesome! Thanks for the help, I'll consider updating after I make sure everything is backed up. Super nice to know what the source of the problem is.

**Comment by deepbluev7** [comment]
No worries, we get that issue reported every few months :D

**Comment by awesomehaze** [comment]
Updated Agesa, everything works great! Maybe add this to the documentation somehow?
