### ISSUE TITLE
How to create a development environment on linux

### ISSUE THREAD

**Issue by salahmak** [Nheko-Reborn/nheko#522]
Hi, I'm looking into exploring the code of nheko and contributing to the project, but i'm getting kinda confused on what's the best way to create a development environment for it. I mean, I'm looking for the best way to compile the app after changing some code, i have tried some ways but I keep getting a large executable (around 200mb) which i don't think is good for development purposes, I think i have all build dependencies listed in the readme installed, and here are the approaches I have considered so far:
```bash
cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug
cmake --build build
```
when using the commands above to compile, it compiles some sources and at around 41% it fails with this error: https://pastebin.com/H0gFrHsM

so then i have tried the second approach:
```bash
cmake -S. -Bbuild -DHUNTER_ENABLED=ON -DBUILD_SHARED_LIBS=OFF -DUSE_BUNDLED_OPENSSL=OFF
cmake --build build --config Debug
```
this gets the job done, it compiled the project after a long time but it then linked everything to the executable, which resulted in a huge executable (230mb) which i don't think is practical since I am just launching the app locally also i have noticed that the installed executable under /usr/bin is only 8mb, so that's why I have decided to ask here for the best approach to build the app since I'm not so familiar with cmake.

Thanks in advance

**Comment by deepbluev7** [comment]
If you have most of the dependencies available, using just the bundled mtxclient and otherwise disabling hunter is usually a good idea. In your first case it failed, because the mtxclient version on your system is too old, the following command may work:

```
cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DUSE_BUNDLED_MTXCLIENT=ON -DUSE_BUNDLED_LMDBXX=ON
cmake --build build
```

Otherwise it is usually easier to provide such support via matrix, so I'd suggest you join #nheko:neko.im, so that we can work out any issues.

There is also nothing wrong with your second approach. Yes, the binary will be huge, because everything is built into the executable and you are building a debug version, but that doesn't cause that many issues in a development build and makes debugging a bit easier.

**Comment by salahmak** [comment]
i'm trying to register on the neko.im homeserver but it won't for some reason (I'm new to the matrix world, so it is kinda confusing)

**Comment by deepbluev7** [comment]
The nheko.im server currently doesn't have open registration, but you can join that room from any matrix homeserver (unless the admins disabled federation).
