### ISSUE TITLE
Close chat when pressing esc. Start nheko with closed chat.

### ISSUE THREAD

**Issue by fgaz** [Nheko-Reborn/nheko#55]
Sometimes I want to keep nheko's window open without marking anything as read. It would be nice if nheko did not open any chat at startup (or category change) and closed any open one when pressing esc (~~like when pressing the "home" button on riot desktop/web~~ it got deleted :( ).

edit: the home button was removed from riot (now element), but you can get a similar effect by pressing the communities button. telegram desktop does this well (press esc)

**Comment by deepbluev7** [comment]
Nheko starts now with a closed chat. You can't close a chat though.

**Comment by deepbluev7** [comment]
You can close a chat by clicking on it now. Not with escape though, since I think that conflicts with too many other uses of that shortcut.

**Comment by fgaz** [comment]
Thanks! To be clear what I had in mind was that esc would work only when no other stuff where esc can act is open.

There is also the other half of the ticket:

> It would be nice if nheko did not open any chat at startup

Is that implemented too?

**Comment by deepbluev7** [comment]
The start with no chat open was done for a while already.

The reason I think escape is a bad idea to close a room is that escape is used for the following things already:

- closing overlays like the image viewer
- closing popups, like the emoji completer
- cancelling a reply or edit
- closing settings windows

All of those are done in an open room and it would really annoy me, if I would close my room by accident, when I just wanted to close the emoji completer and cancel an edit, just because I hit the button one time too many and there is no easy way to get back to where I was in the room.

**Comment by fgaz** [comment]
Makes sense, thanks for the explanation! By the way in eg. telegram desktop this is handled by remembering the position in the chat and restoring it when reopening the chat

**Comment by deepbluev7** [comment]
Maybe in the future, if we find a reliable way to scroll to a specific position. Currently for some reason all approaches don't seem to work correctly.

**Comment by LorenDB** [comment]
At risk of bumping an old, closed issue, rooms are now closable via Ctrl+W.

**Comment by fgaz** [comment]
That's great, thanks a lot!
