### ISSUE TITLE
Apple Silicon / M1 / ARM64 Mac Builds

### ISSUE THREAD

**Issue by nikhiljha** [Nheko-Reborn/nheko#563]
**Is your feature request related to a problem? Please describe.**
Nheko works on newer Macs, but requires Rosetta. Running in emulation isn't ideal.

**Describe the solution you'd like**
Provide aarch64 builds for Macs without Intel processors.

**Describe alternatives you've considered**
Alternatively, ship a combined ("Universal") binary with both the Intel and aarch64 binaries, instead of adding a new one.

**Comment by deepbluev7** [comment]
Sadly we don't have any M1 hardware to build on yet... Maybe one day, when we'll get one for cheap or we could try to make a donation goal for this.

**Comment by deepbluev7** [comment]
Actually, maybe we can cross-compile it, but we would still have no hardware to test on? I'll need to talk with @redsky17 about that :D

**Comment by Techcable** [comment]
This issue is important to me mainly for power efficiency (as I explain below).

## Power Effiency in M1 Macs
Rosetta emulation is significantly more power-intensive (by up to a factor of 10) than a Apple Silicon apps mac.

Emulators like Rosetta comes with a good deal of natural power overhead.

However, the problem goes even deeper. M1 Macs have two sets of CPU cores: "performance cores" and "efficiency cores". The "performance cores" are (obviously) faster and focused on computationally intensive tasks. They are responsible for the big speed gains.

The efficiency cores are focused on background tasks and are about 10x more power efficient than the performance cores (according to apple). The efficiency cores are excellent for background threads. They are responsible for a very large part of the M1 Macs power efficiency.

The thing that makes rosetta emulation so power-inefficient is that it locks all threads to the performance cores. This prevents any backround threads from using the "efficency" cores. At least officially to apple, the power-efficiency difference between the two can be 10x (and anecdotally this seems to be correct).

Right now Nheko is using 10 threads. I suspect most of them are low-priority background tasks, however none of them can use "efficiency" cores.

Anecdotally, apps that switch from Intel to Apple Silicon see a massive difference in power efficiency and a large reduction in CPU time. Even Discord became much more power-efficient.

## Virtualization & Cross-Compilation
I know nothing about this, except that Apple made a serious effort to support this due to the number of developers using intel macs.

I will say that compiling from M1 mac => Intel mac (Universal binary) is almost trivial. Apple has intentionally made that easy to entice developers towards M1.

I have a M1 Mac and might be able to help you look into this, but be aware I know very little about apple-specific development environment :(

## CI options & Rental M1 Macs
Here is a basic overview of the options for M1 Macs as a service (some free, some cheap):
1. [Cirrus CI](https://cirrus-ci.org) is an overall amazing service and has recently added M1 support 😉 
    - This is (obviously) free for open source and appears the first CI to support M1 Macs without requiring you to bring your own infrastructure :)
2. MacStadium is a trusted provider of dedicated macs. This is prohibitively expensive to pay yourself. However they have a generous [Open Source Program](https://www.macstadium.com/opensource) 
   - Unlike travis-ci, this does not seem particularly difficult to apply. If you get in - then you're set!
3. The "Scaleway" company is focussed on ARM-hosting and offers the ability to [rent a virtual M1 Mac](https://www.scaleway.com/en/hello-m1/). They beat AWS to be first to the market on this. Pricing is 0.10€/hour which is very reasonable. Looks like a very legitimiate company. Found article about it [in computewrold](https://www.computerworld.com/article/3605768/how-to-rent-a-virtual-m1-mac-mini-for-12-cents-an-hour.html)
5. I feel obligated to mention AWS. They offer the ability to rent [M1 Mac EC2](https://aws.amazon.com/ec2/instance-types/mac/) instances for what appears to be $0.65 hourly. AWS pricing is notoriously difficult to understand but it falls under the "dedicated" server section. I think that just means you don't use a VM (p
    - I don't know why it's 65x as expensive as the "Scaleway" service. I think AWS is just greedy......

According to AWS website for renting EC2 Macs
 > Billing for EC2 Mac instances is per second with a 24-hour minimum allocation period to comply with the Apple macOS Software License Agreement.

This "macOS license agreement" and minimum allocation agreement applies to Scaleway too. The minimum rental period is always

This means the cost for the AWS minimal rental period is: $.65 * 24 hours = $15.6  per day

The cost for the Scaleway minimum rental period would be: .10 euros * 24 hours = 2.4 euros per day = 2.43

Between the two paid services, the choice seems pretty obvious (especially given AWS reputation).

In addition to being (relatively) cheap, Scaleway also offer an [Open Source Program](https://www.scaleway.com/en/about-us/open-source-program/) although it doesn't appear to be as generous as the MacStadium one.

Note that AWS offers a free trial period for M1 Macs but there appears to be some sort of commitment that goes beyond their normal free trial.

## Conclusions
In MAtrix chats mentioned something about concerns about giving release-signeing keys to untrusted CIs. That may be a problem with Cirrus if you don't trust them 😦 Still, you could produce unsigned release binaries (maybe better than nothing?)

I am cheap (and it sounds like you are too), so we probably don't want to pay for dedicated CI servers!

In general my recommendations for CIs are as follows. These could provide solutions for M1 macs on every build:

1. Try out Cirrius CI. They are free & no-application needed. Even if you don't trust them with release keys you'll get experience building & testing on M1 macs.
   - If you do end up trusting them with your release keys, the whole problem is solved ;)
2. Apply for MacStadium Open source program. They seem the most generous, and you can get a M1 Mac for your poject, then your problems disappear 😉 

If neither of those two options fail (or you don't trust Cirrius CI with release keys), you are going to need to rent a M1 mac to build release versions of your binaries.

It seems like scaleway is the obvious choice here. Paying $2.43 for a 24-hour rental does not seem that bad (and you get full dedicated access) and you would only need to do this for release builds.

At this point you would kind of be compromising and running CI builds only Intel macs, but doing release builds as Apple Silicon/universal binaries.

## Sponsorship Offer
I could possibly consider sponsoring you on this if you can keep costs <$5 a month :)

This issue is clearly important to me if I am to run Nheko in the background all day.

However I can't guarantee anything long-term or forever (my budget is tight), so please don't rely entirely on me.

Right now I tend to occasionally check-in `element.io` instead of keeping a Matrix client open all the time. Not great, but it kind-of works....

**Comment by deepbluev7** [comment]
Not signing Nheko sadly isn't really an option anymore, since that can't show notifications and needs to prompt 5 times to access the keyring...

**Comment by redsky17** [comment]
I'll look into the MacStadium option.  I didn't realize they had such a generous program offered for Open Source software, and I know that they're generally trusted in the community.  I've heard lots of stories from developers who use MacStadium in much the same fashion as we would.

I'll update once I hear back from about my application from MacStadium.

**Comment by redsky17** [comment]
I know it has been a while for this issue.  MacStadium never got back to me on my request for their open source program.  So, we're back to square one =D

**Comment by Techcable** [comment]
> I know it has been a while for this issue. MacStadium never got back to me on my request for their open source program. So, we're back to square one =D

What about CirrusCI? They have free [M1 Mac VMs](https://cirrus-ci.org/guide/macOS/) for open-source projects.

**Comment by redsky17** [comment]
Hey @Techcable thanks for the suggestion!  I went ahead and signed up with cirrus yesterday and was able to build nheko on apple silicon!  Do you want to try DMG to make sure it works correctly?  I'm not 100% sure if everything got packaged up correctly or not in the nheko.app.  Here's a link to the build: https://matrix.to/#/%23nheko-nightlies%3Aneko.dev/%24Vtvgnp-oRRzITE4u7zXixO8peg-gvZpFSO7EWfkRYRU?via=nheko.im&via=matrix.org&via=with.parts&via=neko.dev

It's code-signed and everything, too, so you shouldn't have to worry about that.

**Comment by Techcable** [comment]
> Hey @Techcable thanks for the suggestion! I went ahead and signed up with cirrus yesterday and was able to build nheko on apple silicon! Do you want to try DMG to make sure it works correctly? I'm not 100% sure if everything got packaged up correctly or not in the nheko.app. Here's a link to the build: https://matrix.to/#/%23nheko-nightlies%3Aneko.dev/%24Vtvgnp-oRRzITE4u7zXixO8peg-gvZpFSO7EWfkRYRU?via=nheko.im&via=matrix.org&via=with.parts&via=neko.dev
> 
> It's code-signed and everything, too, so you shouldn't have to worry about that.

Unfortunately, this crashes on my laptop. Looks like a problem with dynamically linking QT  😦 

Here is a screenshot of the console (GUI fails too):

<img width="1108" alt="Screen Shot 2022-10-21 at 2 23 00 PM" src="https://user-images.githubusercontent.com/4615889/197291371-a213843b-f398-4f81-82b5-d8061ecb93ac.png">

Here's the output of `otool -L /Applications/Nheko.app/Contents/MacOS/nheko` (shows static libraries):
```
/Applications/Nheko.app/Contents/MacOS/nheko:
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1858.112.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 23.0.0)
	/System/Library/Frameworks/UserNotifications.framework/Versions/A/UserNotifications (compatibility version 1.0.0, current version 1.0.0)
	/opt/homebrew/opt/qt@5/lib/QtMacExtras.framework/Versions/5/QtMacExtras (compatibility version 5.15.0, current version 5.15.5)
	/opt/homebrew/opt/qt@5/lib/QtSvg.framework/Versions/5/QtSvg (compatibility version 5.15.0, current version 5.15.5)
	/opt/homebrew/opt/qt@5/lib/QtConcurrent.framework/Versions/5/QtConcurrent (compatibility version 5.15.0, current version 5.15.5)
	/opt/homebrew/opt/qt@5/lib/QtMultimedia.framework/Versions/5/QtMultimedia (compatibility version 5.15.0, current version 5.15.5)
	/opt/homebrew/opt/qt@5/lib/QtQuickControls2.framework/Versions/5/QtQuickControls2 (compatibility version 5.15.0, current version 5.15.5)
	/opt/homebrew/opt/qt@5/lib/QtQuickWidgets.framework/Versions/5/QtQuickWidgets (compatibility version 5.15.0, current version 5.15.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
	/System/Library/Frameworks/LDAP.framework/Versions/A/LDAP (compatibility version 1.0.0, current version 2.4.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1858.112.0)
	/opt/homebrew/opt/qt@5/lib/QtQuick.framework/Versions/5/QtQuick (compatibility version 5.15.0, current version 5.15.5)
	/opt/homebrew/opt/qt@5/lib/QtQmlModels.framework/Versions/5/QtQmlModels (compatibility version 5.15.0, current version 5.15.5)
	/opt/homebrew/opt/qt@5/lib/QtQml.framework/Versions/5/QtQml (compatibility version 5.15.0, current version 5.15.5)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 60158.100.133)
	/opt/homebrew/opt/qt@5/lib/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.15.0, current version 5.15.5)
	/opt/homebrew/opt/qt@5/lib/QtGui.framework/Versions/5/QtGui (compatibility version 5.15.0, current version 5.15.5)
	/opt/homebrew/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork (compatibility version 5.15.0, current version 5.15.5)
	/opt/homebrew/opt/qt@5/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.15.0, current version 5.15.5)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2113.40.126)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**Comment by redsky17** [comment]
Bummer.  I was worried about rpath issues >.<.  The libraries are packed into the .app file, but it’s looking for the qt libs at the path that they are installed on the cirrus VM.  If you wanted to give it a shot, you can use otool to edit the lookup path for those libraries.  I’m not sure if that’ll invalidate the code signature or not though

**Comment by Techcable** [comment]
> Bummer. I was worried about rpath issues >.<. The libraries are packed into the .app file, but it’s looking for the qt libs at the path that they are installed on the cirrus VM. If you wanted to give it a shot, you can use otool to edit the lookup path for those libraries. I’m not sure if that’ll invalidate the code signature or not though

There seem to be two issues with the app you linked.

The first one is that the packed libraries are compiled for x64, not ARM:

```
$ file /Applications/Nheko.app/Contents/MacOS/nheko
/Applications/Nheko.app/Contents/MacOS/nheko: Mach-O 64-bit executable arm64
$ file /Applications/Nheko.app/Contents/Frameworks/QtCore.framework/QtCore
/Applications/Nheko.app/Contents/Frameworks/QtCore.framework/QtCore: Mach-O 64-bit dynamically linked shared library x86_64
$ file /Applications/Nheko.app/Contents/Frameworks/libpng16.16.dylib
/Applications/Nheko.app/Contents/Frameworks/libpng16.16.dylib: Mach-O 64-bit dynamically linked shared library x86_64
```

These are not universal binaries. Those have a different format.

The second problem is that the ARM64 binary is linked with absolute paths. There is no reference to `@executable_path` or `@rpath` at all.

Here's an comparison of the linker commands (output given from running `otool -l`:
<details>
   <summary>ARM64 linker commands</summary>
```
Load command 25
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /opt/homebrew/opt/qt@5/lib/QtQuick.framework/Versions/5/QtQuick (offset 24)
   time stamp 2 Wed Dec 31 17:00:02 1969
      current version 5.15.5
compatibility version 5.15.0
Load command 26
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name /opt/homebrew/opt/qt@5/lib/QtQmlModels.framework/Versions/5/QtQmlModels (offset 24)
   time stamp 2 Wed Dec 31 17:00:02 1969
      current version 5.15.5
compatibility version 5.15.0
Load command 27
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /opt/homebrew/opt/qt@5/lib/QtQml.framework/Versions/5/QtQml (offset 24)
   time stamp 2 Wed Dec 31 17:00:02 1969
      current version 5.15.5
compatibility version 5.15.0
Load command 28
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name /System/Library/Frameworks/Security.framework/Versions/A/Security (offset 24)
   time stamp 2 Wed Dec 31 17:00:02 1969
      current version 60158.100.133
compatibility version 1.0.0
Load command 29
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name /opt/homebrew/opt/qt@5/lib/QtWidgets.framework/Versions/5/QtWidgets (offset 24)
   time stamp 2 Wed Dec 31 17:00:02 1969
      current version 5.15.5
compatibility version 5.15.0
Load command 30
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /opt/homebrew/opt/qt@5/lib/QtGui.framework/Versions/5/QtGui (offset 24)
   time stamp 2 Wed Dec 31 17:00:02 1969
      current version 5.15.5
compatibility version 5.15.0
```
</details>
<details>
<summary>x64 linker commands</summary>
```
Load command 24
          cmd LC_LOAD_DYLIB
      cmdsize 104
         name /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (offset 24)
   time stamp 2 Wed Dec 31 17:00:02 1969
      current version 1856.105.0
compatibility version 150.0.0
Load command 25
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name @executable_path/../Frameworks/QtQuick.framework/Versions/5/QtQuick (offset 24)
   time stamp 2 Wed Dec 31 17:00:02 1969
      current version 5.15.5
compatibility version 5.15.0
Load command 26
          cmd LC_LOAD_DYLIB
      cmdsize 104
         name @executable_path/../Frameworks/QtQmlModels.framework/Versions/5/QtQmlModels (offset 24)
   time stamp 2 Wed Dec 31 17:00:02 1969
      current version 5.15.5
compatibility version 5.15.0
Load command 27
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name @executable_path/../Frameworks/QtQml.framework/Versions/5/QtQml (offset 24)
   time stamp 2 Wed Dec 31 17:00:02 1969
      current version 5.15.5
compatibility version 5.15.0
Load command 28
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name /System/Library/Frameworks/Security.framework/Versions/A/Security (offset 24)
   time stamp 2 Wed Dec 31 17:00:02 1969
      current version 60157.60.19
compatibility version 1.0.0
Load command 29
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name @executable_path/../Frameworks/QtWidgets.framework/Versions/5/QtWidgets (offset 24)
   time stamp 2 Wed Dec 31 17:00:02 1969
      current version 5.15.5
compatibility version 5.15.0
Load command 30
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name @executable_path/../Frameworks/QtGui.framework/Versions/5/QtGui (offset 24)
   time stamp 2 Wed Dec 31 17:00:02 1969
```
</details>

Notice the use of a relative path based on `@executable_path` in x64 binary that's absolute in ARM64. Even if the included QT libraries were compiled for arm64 instead of x64, the linker still wouldn't detect it.

I suspect this is a problem with the way CMake is linking the app...

Maybe I'll try forking the branch and playing around with it myself 😉

**Comment by deepbluev7** [comment]
Yeah, the problem is that the dmg is signed and bundles on an x86 system, so it pulls in those libraries.

**Comment by redsky17** [comment]
I have updated the build process to bundle everything in each respective CI platform (cirrus for arm64, gitlab for x86_64).  Hopefully... HOPEFULLY, I fixed this issue.  I have a new nightly that I need test subjects for: 
https://matrix.to/#/%23nheko-nightlies%3Aneko.dev/%24_2Odc8R9hIrQcuvr7k3fDXLJ-ntD8SUaWp1jw7Nupmw?via=nheko.im&via=matrix.org&via=with.parts&via=neko.dev

**Comment by LorenDB** [comment]
Apparently there were no showstopper problems! :)
