### ISSUE TITLE
Allow reply in notification without quoting

### ISSUE THREAD

**Issue by yuyichao** [Nheko-Reborn/nheko#621]
**Is your feature request related to a problem? Please describe.**
When replying in the notification popup, the text is automatically quoted, even [when it's not shown](https://github.com/Nheko-Reborn/nheko/issues/620). For 1-1 chat this can often be unnecessary/annoy and even in a multi-people chatroom, quoting is often not required when replying to the last message.

**Describe the solution you'd like**
Changing the default behavior and/or an option/separate button to reply without quoting.

**Comment by deepbluev7** [comment]
The messaging around it does suggest, that you are replying, which in my opinion should always send a matrix reply. We could however consider just not rendering replies, if they are a reply to the message directly above? Would that be an acceptable solution?

**Comment by yuyichao** [comment]
I don't think the display is the thing to change, since the other user (also me on different devices) may not be all using the same client. On element the text appears to be quoted as well even for replying to the previous message so I don't think that should be changed. (I want to make sure I'm seeing something similar to the other side so as not to make it harder to read for them either...)

**Comment by deepbluev7** [comment]
Well, we are not really quoting the other message, we are setting a relation to the previous event. It is up to the clients how to render that nicely and I think we should always set the relation, since federation issues may lead to others seeing events in between and a client can always improve, how they render replies instead, if how they look is an issue.

On the other hand, disabling the relation may be useful for IRC rooms, so such an option could be useful. I don't like having an option for everything though, since it is hard to test...

**Comment by deepbluev7** [comment]
Not doing this, because I think replies should always send replies.
