### ISSUE TITLE
Messages are sent to unverified sessions

### ISSUE THREAD

**Issue by pcworld** [Nheko-Reborn/nheko#636]
### Describe the bug
With Nheko 0.8.2, messages are sent to unverified sessions (without any kind of warning or indicator), thus confidentiality is broken.

In 9f30a30e535556cc4b57eecc9a34572dd06017eb, the warning "and media are encrypted, nheko doesn't verify who gets the messages" has been removed. Does this need unreleased commits (after a quick look I haven't found a related commit)?

I'm also not quite sure how device verification is supposed to work in Nheko, so maybe I'm misunderstanding the workflow (which might be considered a UI issue).

### To Reproduce
1. I (user B) have a contact A (which for demonstration purposes I control) that I have verified through Element Web.
2. On app.element.io, I log in with A, creating a new session for A. But I do *not* cross-sign this session from another session of A, and also do not verify this from a client of mine (user B).
3. In Nheko, I now send a message to A.
4. The message is delivered to A without any kind of warning, and the message successfully decrypts in the unverified session of A.

### Expected behavior
Nheko does not encrypt the message to the unverified session of A.

### System:

- Nheko version: 0.8.2
- Installation method: Alpine repo
- Operating System: postmarketOS Edge

**Comment by deepbluev7** [comment]
I don't think any client actually does this by default. You can now verify users in Nheko, so you can see, if an unknown device is in the room, but Nheko has no button yet to only send messages to verified devices. In Element you can optionally enable that, but it is disabled by default. We certainly need to improve there, but the warning message got removed, because we now are at the same behaviour as other E2EE Matrix clients by default. I want to add an introduction page, that allows you to enable or disable such a setting on first start though in the near future.
