### ISSUE TITLE
Key Verification Support

### ISSUE THREAD

**Issue by redsky17** [Nheko-Reborn/nheko#70]
Nheko currently doesn't support Key Verification the same way Riot does.  Right now, it automatically approves key verification requests, which is not ideal.

Nheko should at a minimum support 'legacy verification' the way Riot does.  Ideally, nheko would also support pop-up dialog that automatically comes up when m.room_key_request is received.  Additionally, consider implementing the emoticon-style validation (in a way that can be configured in the settings):
https://docs.google.com/document/d/1SXmyjyNqClJ5bTHtwvp8tT1Db4pjlGVxfPQNdlQILqU/edit#heading=h.vdxlt7l17cal

https://github.com/matrix-org/matrix-doc/issues/1267

**Comment by GreenReaper** [comment]
Just ran into something like this myself, although it might be a separate issue - the host's certificate had expired and Riot.im's Android client popped up a warning while Nheko seemingly did not give any indication of a problem.

The Riot Android client actually wasn't very specific about what the problem was, just that the key was not valid, and I assumed that it was because a renewal had change the key since it popped it up; however it was just out of date and once I reopened the client it started working. Meanwhile Nheko started giving me messages without a restart (I can't tell for sure that, but I did receive a message on Android that I sent via Nheko during the period the Android client was warning about a security concern).

**Comment by deepbluev7** [comment]
Emoji and Digit verification are implemented, missing parts currently are:

- Cross-sign via self and user signing key (and request or read those keys from SSSS)
- Optionally don't share keys with untrusted devices
- Share secrets with own trusted devices and room keys with trusted devices
- Show if a message is sent from a verified user

Anything else?

**Comment by lbeltrame** [comment]
@deepbluev7 Perhaps, force request of  keys of single messages (unless it falls under your first or third point).

**Comment by deepbluev7** [comment]
Keys should get automatically requested, when a message fails to decrypt. Only issue currently is, that the message doesn't get rerendered, when the key arrives, but I'll do that at some point too.

**Comment by deepbluev7** [comment]
So most of this is done now. I think for any remaining issues, I'll just file separate issues to track them.
