### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by Bar2ly** [Nheko-Reborn/nheko#717]
Hi, I've been trying to register for a while and I don't know how what to put in "Homeserver". I'm kinda noob to this and the answer will be obvious but I really don't know what to do

**Comment by deepbluev7** [comment]
You need to pick a public server or host your own. The most popular server is https://matrix.org, but Nheko currently can't register on that server, because they changed some of their registration requirements. There are a few more servers listed here: https://publiclist.anchel.nl/ (and on similar lists). Some of them require Single Sign on (i.e. login via Email, Google, Mozilla, or similar). If you are having trouble registering, you might want to try signing up using https://app.element.io/

**Comment by Bar2ly** [comment]
Thank you, I managed to join with nheko with the instructions you provided. Thanks for the help deepbluev7

**Comment by deepbluev7** [comment]
No worries, I hope you enjoy Matrix!
