### ISSUE TITLE
Default to system theme if QT_QPA_PLATFORMTHEME is set

### ISSUE THREAD

**Issue by redsky17** [Nheko-Reborn/nheko#72]
On first startup (before user has selected any preferences themselves), default to the system theme option if the QT_QPA_PLATFORMTHEME  environment variable is set.

**Comment by deepbluev7** [comment]
This was fixed in  d5bb093, so I'm closing this for now. Please reopen, if anyone has an issue with the current implementation!

**Comment by alexander255** [comment]
Will this automatically use the system theme on KDE Plasma?

At least on my Plasma Wayland installation `QT_QPA_PLATFORMTHEME` is not set. For me, my first impression of nheko wasn't all that great initially since it's theme looked really out of place, but with the system theme integration it fits perfectly!
