### ISSUE TITLE
No startindex in formatted_body rendering

### ISSUE THREAD

**Issue by pizdjuk** [Nheko-Reborn/nheko#793]
### Describe the bug

Nheko sends not the message that entered on readline.

### To Reproduce

a. Open some chat
b. write following text:

Test a bug ENTER
1. test 1 ENTER
2. test 2 ENTER

c. The text that appears in chat will be:

1. test 1
1. test 2

### Version

0.8.2

### Operating system

Linux

### Installation method

AppImage

### Desktop Environment

MATE with i3 window manager

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
I can't reproduce it, can you try again and maybe send a video of it? I'm pretty sure I followed your steps exactly.

**Comment by pizdjuk** [comment]
here is the video:

https://user-images.githubusercontent.com/35386958/140831182-cea87538-1450-4e0e-8dc1-486f38434f6e.mp4

**Comment by pizdjuk** [comment]
Btw. this seems to appear somekind in a browser too.... Could be the toolkit bug?

**Comment by deepbluev7** [comment]
Oh, you meant the start index is wrong in the enumeration! That is a limitation of the text rendering we use. Starting a message with a number actually makes it a numbered list, and they always start with 1 (because we can't render the start index). If you press "Shift+Enter" and add another line starting with 1., it will enter a 2 after sending. You can suppress that using /plain.

**Comment by deepbluev7** [comment]
I fixed this in Qt6.6, this will work once your Nheko uses Qt6.6: https://codereview.qt-project.org/c/qt/qtbase/+/460444
