### ISSUE TITLE
Join room popup goes beyond edge of screen in Wayland while window is maximized

### ISSUE THREAD

**Issue by bbhtt** [Nheko-Reborn/nheko#892]
### Describe the bug

The join/create room popup goes beyond the edge of the screen when Wayland is forced onto Nheko. As a result the second option in that menu is not visible until the Nheko window is minimized. I'm not sure if this is a Qt bug or Nheko... It doesn't happen when using the X11/xwayland backends.

### To Reproduce

1. Run `$ flatpak run --env=QT_QPA_PLATFORM=wayland io.github.NhekoReborn.Nheko` or `$ QT_QPA_PLATFORM=wayland nheko`

### Expected behavior

The popup should be displayed above the "+" button so that all options in that menu are visible.

### Screenshots

Wayland:

![Screenshot_Wayland](https://user-images.githubusercontent.com/62639087/149147839-b7cacab8-9c8a-4700-8292-08ad88330d91.png)

X11:

![Screenshot_X11](https://user-images.githubusercontent.com/62639087/149147875-4a5c9472-088f-4206-9e2e-c2f455ed09e0.png)

### Version

0.9.1-b9a4f36 | Linux

### Operating system

Linux

### Installation method

Flathub

### Desktop Environment

GNOME/Wayland

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
See #559, https://bugreports.qt.io/browse/QTBUG-87303, #849. It's an upstream qt bug and appears in a few other cases as well. Should be fixed in Qt6, not sure if it will be backported to Qt5.15 by KDE. Anyway, I'll close this, since there are a few other issues like that already and they all have the same causes.
