### ISSUE TITLE
Use twemoji for verification emoji

### ISSUE THREAD

**Issue by ara4n** [Nheko-Reborn/nheko#919]
### Describe the bug

Whatever font nheko uses for emoji verification doesn’t match twemoji, as used by other clients. While the Matrix spec doesn’t yet mandate twemoji, it probably should - as otherwise users will get confused trying to visually compare emoji which cosmetically differ:

https://twitter.com/NireBryce/status/1489099092575858707

Instead, perhaps consider twemoji (or matrix.org can ship a subset of twemoji which just includes the verif emoji)

### To Reproduce

https://twitter.com/NireBryce/status/1489099092575858707

### Version

unknown

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
I'm a bit conflicted on this. I think using the systems font of emoji is easier to recognize for a user and makes them trust the verification message more. If the verification message uses a different emoji font than Nheko or your system does otherwise, that is also potentially confusing. Linux distributions also don't like it, if we bundle a font, so we would need to require packagers to add a dependency on the font.

On the other hand I can see how it can be confusing to see emojis in different fonts on both sides.

But in the end, emojis were chosen to be easily recognizable shapes. Not because they are exactly the same images on both sides, but because they have distinct meanings. That's why the subset of emojis used in the verification is selected to be as distinct from each other as possible too.

I'll need to think about this. Especially since most people don't seem to have an issue with this. One person complaining on Twitter might not be the best indication of good design. Maybe I'll just add a disclaimer to the verification, that the exact appearance of the emojis depends on your systems font selection.

**Comment by ara4n** [comment]
my reason for raising it is that i've seen the complaint a lot - particularly when Element used different fonts on all 3 platforms.  However, my plan is to subset the necessary glyphs into a ttf, at which point it should be dead easy to use.

In terms of "users will trust the system emoji more", i think that's totally flawed - the user doesn't even necessarily know that it's emoji; they'll just think of it as a series of pics.

**Comment by LorenDB** [comment]
My 2¢: if we are mandating a certain emoji, maybe make sure it is a FOSS set so that we keep everyone happy. I'm personally fine with non-FOSS but some people would get worked up over that point.

I'm not even sure what the EmojiOne license is, so maybe this is a moot point.

**Comment by ara4n** [comment]
just realised i systematically meant to say twemoji (which is what we use for element; i should know, given i added it :/) rather than emojione - sorry for confusion.

**Comment by LorenDB** [comment]
(I personally would prefer EmojiOne to twemoji due to looks :smiley:)
