### ISSUE TITLE
Missing AppImage download

### ISSUE THREAD

**Issue by Tcll** [Nheko-Reborn/nheko#988]
### Describe the bug

your download pages claim I can download an AppImage, but the only download I can find for Linux is FlatPak, which I can't use (not enough room to install the daemon)

where can I download the latest AppImage so I can try the latest version?
or at the very least download an ELF.tgz

### To Reproduce

1. Go to any one of your download pages or search for "nheko AppImage" in your search engine of choice
2. Click on the myriad of links taking you to the github releases page on here
3. Scroll down to the assets for the latest release
4. See that there's no appimage available

### What happened?

a missing binary

### Expected behavior

a binary AppImage (or ELF.tgz) download

### Version

0.9.2

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
unavailable, can't obtain a working binary to run
```

**Comment by Tcll** [comment]
also I would've filled the operating system with "Linux" and the installation method as "AppImage" but the menus are aesthetic only and don't do anything

**Comment by redsky17** [comment]
We stopped providing AppImages right around the 0.9.0 release.  So older releases still have them available, but new ones do not.  We encountered way too many issues with AppImages and neither Nico nor myself use them, so we didn't want to provide something that we couldn't fully support.

**Comment by Tcll** [comment]
it's easier to build appimages with AppImageKit than docker
docker is actually kindof a joke when it comes to them because of improper AppRun binaries that don't actually work properly

I actually use this myself and it's really easy to work with appimagetool
but you have to know how to structure the AppDir before running it
https://github.com/AppImage/AppImageKit/releases

could I at least request an ELF.tgz release if AppImage is too much of a hassle??

**Comment by redsky17** [comment]
It's not building the AppImage that is the hassle, it's the random issues that various parts of the AppImage have when interacting with the underlying system that is the hassle.

What exactly do you mean by an ELF.tgz release?  The source tarballs are attached to each release as it is.  I think if we released ELF binaries directly, they wouldn't work in a lot of cases since they would depend on the exact platform they were built on.  We would also need to static link everything, which would make the resulting binary more or less huge.

**Comment by deepbluev7** [comment]
Note that we did use appimagebuilder before, but that tool didn't properly isolate all dependencies either.

**Comment by Tcll** [comment]
@redsky17 thanks for explaining, yeah Qt rather sucks, that I understand full well
it's sad you have to do so much with a library that's supposed to be cross-platform just to ensure it doesn't break
(especially when it comes to that stupid xcb plugin that gets me literally every time)

... I know this will require a ton of overhaul work...
but could I perhaps suggest FLTK there??
that library shouldn't give you nearly as many issues as Qt does
plus you could shave a good 200MB or so off your package size...
___

anyways, yes, ELF.tgz would be a static binary
no different from what you can download at blender.org

I'm only requesting it because I aim to provide as such with my apps

you can build the ELF with compatibility, especially if you build with musl
which should solve the problems on most major distros (at worst, maybe not broken distros like Manjaro)
but in fact the only ones that should have any problems would be weird stuff like Alpine or Solus

**Comment by deepbluev7** [comment]
You try writing a complex application in FLTK and come back to me please. It's not feasible at all. The problem isn't Qt, the problem is AppImages. They don't have a proper way to package them and they don't isolate all dependencies. They are broken by design. And a packaged elf will have similar issues, because an AppImage is barely anything different. If you want to see such a package, I suggest you build it yourself and open a pull request. We clearly have spent enough time dealing with AppImages and since flatpaks do pretty much everything better than AppImages, there is no reason for us to provide anything else using our spare time. We'd rather like to spend that time doing something useful. If you are ideologically opposed to flatpaks, contribute a working AppImage, test it with every release and fix the issues you encounter with it. We prefer pragmatic solutions, not ideological ones.

**Comment by Tcll** [comment]
relax, I'm trying not to be ideological

in fact the suggestion to FLTK is actually practical
I did say it would require a lot of work...
but it would solve a lot of the dependency issues you'd experience with appimages
as you'd be using libraries that are actually portable and designed for such implementations.

and yes, I do understand the frustrations after building my own widget library in OpenGL for my own equally complex applications.
if you need proof to validate my claim, I'm building this to replace Nemo with:
![](https://user-images.githubusercontent.com/773959/156290320-b7bfacdd-3a3f-4347-b919-445b40436a8b.png)
everything I'm using is designed to be as portable as possible (aside from GLFW, which I'll be replacing with `/tmp/.x11-unix/X0` when I can)

Qt is not portable, thus you have issues with system/version conflicts in appimage integrations.

**Comment by deepbluev7** [comment]
Half of our dependency issues were with gstreamer though or other libraries... Qt is just a small part of it.

**Comment by Tcll** [comment]
honestly I was only kinda guessing with Qt as I've used an earlier appimage that made use of it
I'm not really paying attention to what deps you guys use
but now that you mention gstreamer, I know that's associated with GTK which is yet another not portable nightmare for appimages

unfortunately I'm not certain what to recommend as an alt to gstreamer that's actually portable
best I could think would be ffmpeg, but yeah
kinks that'll have to be worked out in time :P

**Comment by deepbluev7** [comment]
gstreamer is used to do voip calls, ffmpeg doesn't do webrtc and libwebrtc is a pain to use. We don't need to switch toolkits, we can just use proper app containers like flatpak. Those have a buildsystem, that properly isolates the used libraries.

**Comment by Tcll** [comment]
to be fair, anything dealing with web anything is nightmarish in and of itself and probably should be avoided for better alternatives where possible...

I just hope you can get back into building an appimage
or better with ELF.tgz

because I can't use nheko otherwise

**Comment by docop** [comment]
Indeed an appimage can be quite usefull. For a true portable system, you simply plug the usb key and run the appimage file as a portable app. Not having to dwl and install flat stuff taking space and downloading random not used data..
